server.port=8080

# Applicant Details (UPDATE THESE BEFORE DEPLOYING)
app.user.full-name=Preeti
app.user.dob=27022005
app.user.email=preeti1390.be23@chitkarauniversity.edu.in
app.user.roll-number=2311981390
